name: Format, Build, and Commit

on:
  push:
    branches:
      - main

jobs:
  format-build-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: '1.2'

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run format
        run: bun run format

      - name: Run build
        run: bun run build

      - name: Commit changes (if any)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if [[ -n $(git status --porcelain) ]]; then
            git add .
            git commit -m "chore: apply formatting and build output via CI"
            git push
          fi